pipeline {
    agent any

    stages {

        stage('Check Out Application code') {
            steps {
                dir('APP') {
                   git
                }

            }
        }

    }
}
